spring:
  application:
    name: Users-Security-Service
  data: 
   mongodb:
      uri: mongodb+srv://DataAdmin:DataAdmin@cluster0.1eau7.mongodb.net/UserDatabase?retryWrites=true&w=majority
    
server:
  port: 8683