spring:
  application: 
    name: Flight-Booking-Microservice
  data: 
    mongodb:
      uri: mongodb+srv://DataAdmin:DataAdmin@cluster0.1eau7.mongodb.net/FlightDatabase?retryWrites=true&w=majority

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8087